name: Deploy Backend to Windows Server

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Deploy Backend
        run: |
          cd backend
          npm install --legacy-peer-deps
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          npx prisma generate
          npx pm2 restart dayanote-be
